name: Demo App Android Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.2.0"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --coverage
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
          token: "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"
          tag: "v1.0.0"
