name: Demo App Android Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.2.0"
      - run: flutter pub get
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
          token: "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"
          tag: "v1.0.0"
